version: "3.7"

volumes:

  db:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/admin/data/DB

  wb:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/admin/data/WB

networks:
  mynetwork:
    driver: bridge

services:
  
  nginx:
    build: 
      context: ./requirements/nginx
    image: nginx:my 
    container_name: co_nginx
    env_file : ./.env
    ports:
      - 443:443
    volumes:
      - wb:/usr/share/nginx/html
    networks:
      - mynetwork
    depends_on:
      - wordpress
    restart: always

  
  mariadb:
    build:
      context: ./requirements/mariadb
      args:
        - DB_ROOT_PASSWORD=${DB_ROOT_PASSWORD:-default_root_password}
        - DB_USER=${DB_USER:-default_user}
        - DB_USER_PASSWORD=${DB_USER_PASSWORD:-default_password}
        - DB_DATABASE=${DB_DATABASE:-default_database}
    image: mariadb:my 
    container_name: co_mariadb
    env_file : ./.env
    volumes:
      - db:/var/lib/mysql
    networks:
      - mynetwork
    restart: always

    
  wordpress:
    build :
      context : ./requirements/wordpress
      args:
      - DB_ROOT_PASSWORD=${DB_ROOT_PASSWORD:-default_root_password}
      - DB_USER=${DB_USER:-default_user}
      - DB_USER_PASSWORD=${DB_USER_PASSWORD:-default_password}
      - DB_DATABASE=${DB_DATABASE:-default_database}
      - url=${url:-def}
      - title=${title:-def}
      - wordpress_admin=${wordpress_admin:-def}
      - wordpress_password=${wordpress_password:-def}
      - admin_email=${admin_email:-def}
      - DB_HOST=co_mariadb
      - user_mail=${user_mail}
      - WP_user=${WP_user}
      - user_pass=${user_pass}
    image: wordpress:my
    container_name: co_wordpress
    env_file : ./.env
    volumes:
      - wb:/usr/share/nginx/html
    networks:
      - mynetwork
    depends_on:
      - mariadb
    restart: always

    

